// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as IndexRoute from "@/app/(withLayout)/page.info";
import * as AdminRoute from "@/app/(withLayout)/admin/page.info";
import * as AdminHirlevelListaRoute from "@/app/(withLayout)/admin/hirlevel/lista/page.info";
import * as AdminHirlevelUjRoute from "@/app/(withLayout)/admin/hirlevel/uj/page.info";
import * as AszfRoute from "@/app/(withLayout)/aszf/page.info";
import * as HirlevelRoute from "@/app/(withLayout)/hirlevel/page.info";
import * as ReferenciaRoute from "@/app/(withLayout)/referencia/page.info";
import * as TervrajzokRoute from "@/app/(withLayout)/tervrajzok/page.info";
import * as TervrajzokSlugRoute from "@/app/(withLayout)/tervrajzok/[slug]/page.info";
import * as TervrajzokSlugHasonloakRoute from "@/app/(withLayout)/tervrajzok/[slug]/hasonloak/page.info";
import * as TervrajzokSlugKapcsolatRoute from "@/app/(withLayout)/tervrajzok/[slug]/kapcsolat/page.info";
import * as AdminHirlevelElonezetRoute from "@/app/admin/hirlevel/elonezet/page.info";

export const Index = makeRoute(
  "/(withLayout)",
  {
    ...defaultInfo,
    ...IndexRoute.Route
  }
);
export const Admin = makeRoute(
  "/(withLayout)/admin",
  {
    ...defaultInfo,
    ...AdminRoute.Route
  }
);
export const AdminHirlevelLista = makeRoute(
  "/(withLayout)/admin/hirlevel/lista",
  {
    ...defaultInfo,
    ...AdminHirlevelListaRoute.Route
  }
);
export const AdminHirlevelUj = makeRoute(
  "/(withLayout)/admin/hirlevel/uj",
  {
    ...defaultInfo,
    ...AdminHirlevelUjRoute.Route
  }
);
export const Aszf = makeRoute(
  "/(withLayout)/aszf",
  {
    ...defaultInfo,
    ...AszfRoute.Route
  }
);
export const Hirlevel = makeRoute(
  "/(withLayout)/hirlevel",
  {
    ...defaultInfo,
    ...HirlevelRoute.Route
  }
);
export const Referencia = makeRoute(
  "/(withLayout)/referencia",
  {
    ...defaultInfo,
    ...ReferenciaRoute.Route
  }
);
export const Tervrajzok = makeRoute(
  "/(withLayout)/tervrajzok",
  {
    ...defaultInfo,
    ...TervrajzokRoute.Route
  }
);
export const TervrajzokSlug = makeRoute(
  "/(withLayout)/tervrajzok/[slug]",
  {
    ...defaultInfo,
    ...TervrajzokSlugRoute.Route
  }
);
export const TervrajzokSlugHasonloak = makeRoute(
  "/(withLayout)/tervrajzok/[slug]/hasonloak",
  {
    ...defaultInfo,
    ...TervrajzokSlugHasonloakRoute.Route
  }
);
export const TervrajzokSlugKapcsolat = makeRoute(
  "/(withLayout)/tervrajzok/[slug]/kapcsolat",
  {
    ...defaultInfo,
    ...TervrajzokSlugKapcsolatRoute.Route
  }
);
export const AdminHirlevelElonezet = makeRoute(
  "/admin/hirlevel/elonezet",
  {
    ...defaultInfo,
    ...AdminHirlevelElonezetRoute.Route
  }
);

