name: Run Linter
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

defaults:
  run:
    working-directory: ./www

jobs:
  lint:
    name: Run linter
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - uses: actions/setup-node@main
        with:
          node-version: 20
      - run: npm ci
      - name: Super-Linter
        uses: super-linter/super-linter@v6.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: ./
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_CSS: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_PHP_BUILTIN: false
          VALIDATE_PHP_PHPCS: false
          VALIDATE_PHP_PHPSTAN: false
          VALIDATE_PHP_PSALM: false
          VALIDATE_TYPESCRIPT_STANDARD: false
